🐳 chore: try to fix github action failure
ImportError: cannot import name 'Sequence' from 'collections' (/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/collections/__init__.py)

this is caused by mkdocs on py3.10